/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/*.{html,js}"],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      purple: "#3f3cbb",
      midnight: "#121063",
      metal: "#F3D0D7",
      tahiti: "#3ab7bf",
      silver: "#ecebff",
      bermuda: "#78dcca",
      nav: "#131921",
      "bubble-gum": "#0E46A3",
      "search-bar": "#FFEFEF",
      arrow: "#ecf7ff",
      body: "#BAE0B7",
      signbody: "#525561",
      form: "#272A37",
      signtext: "#314160",
      black: "#314160",
      black2: "#000000",
      circle: "#238BE8",
      formcontainer: "#96A0B0",
      link: "#216AAE",
      inputbox: "#323644",
      button: "#1D90F5",
      button2: "#555B69",
    },
    fontFamily: {
      otline: ["Outfit"],
    },
    extend: {},
  },
  plugins: [],
};
